---
title: "Scotland's Gender Equality Index"
subtitle: "Official Statistics"
---

Scotland's Gender Equality Index measures progress towards gender equality in Scotland.  It is designed to represent gender equality numerically, with a score of one indicating no gender equality and a score of one hundred indicating full gender equality. Gender equality is measured across a range of indicators, covering Work, Money, Time, Knowledge, Power and Health. Additional indicators on Violence Against Women and Women-Specific Healthcare are also included. The first release of Scotland's Gender Equality Index was in 2020. We acknowledge that it may not be perfect and there will be some scope for the indicator set to evolve, however it should be noted that any change to the indicator set may affect the Index’s primary purpose which is to measure Scotland’s progress through time towards gender equality.

Official and National Statistics are produced to high professional standards set out in the Code of Practice for Official Statistics. Both undergo regular quality assurance reviews to ensure that they meet customer needs and are produced free from any political interference.

### Correspondence and enquiries

For enquiries about these publications please contact:

Communities Analysis Division  
Telephone: 0131 244 5851  
e-mail: [social-justice-analysis@gov.scot](mailto:social-justice-analysis@gov.scot)

For general enquiries about Scottish Government statistics please contact:  

Office of the Chief Statistician  
Telephone: 0131 244 0442  
e-mail: [statistics.enquiries@gov.scot](mailto:statistics.enquiries@gov.scot)

### How to access background or source data

The data collected for this statistical bulletin may be made available on request, subject to consideration of legal and ethical
factors. Please contact [social-justice-analysis@gov.scot](mailto:social-justice-analysis@gov.scot) for further information. 

### Complaints and suggestions

If you are not satisfied with our service or have any comments or suggestions, please write to the Chief Statistician: 

3WR St Andrews House  
Edinburgh, EH1 3DG  
Telephone: (0131) 244 0302  
e-mail [statistics.enquiries@gov.scot](mailto:statistics.enquiries@gov.scot)

Details of forthcoming publications can be found at [www2.gov.scot/Topics/Statistics/ForthcomingPubs](https://www2.gov.scot/Topics/Statistics/ForthcomingPubs)

### Crown Copyright 2020

You may use or re-use this information (not including logos) free of charge in any format or medium, under the terms of the Open Government Licence. See: [www.gov.scot/crown-copyright/](https://www.gov.scot/crown-copyright/) 

